<?php

namespace App\Services\Attachments;

use App\Models\Attachment;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Livewire\Features\SupportFileUploads\TemporaryUploadedFile;
use Symfony\Component\HttpFoundation\StreamedResponse;

class AttachmentService
{
    /**
     * Upload an attachment.
     *
     * @param Model $owner The attachable model.
     * @param UploadedFile|TemporaryUploadedFile $file The file to upload.
     * @param string|\App\Enums\AttachmentType $type The attachment type.
     * @param array $options Options for upload (e.g. idempotency_key, metadata).
     * @return Attachment
     */
    public function upload(Model $owner, UploadedFile|TemporaryUploadedFile $file, $type, array $options = []): Attachment
    {
        $typeValue = $type instanceof \App\Enums\AttachmentType ? $type->value : $type;
        $idempotencyKey = $options['idempotency_key'] ?? null;
        
        // 1. Check idempotency if provided
        if ($idempotencyKey) {
            $existing = $owner->attachments()
                ->where('type', $typeValue)
                ->where('idempotency_key', $idempotencyKey)
                ->first();

            if ($existing) {
                return $existing;
            }
        }

        $config = config("attachments.types.{$typeValue}");
        $mode = $config['mode'] ?? 'multiple';
        $disk = $config['disk'] ?? config('attachments.default_disk', 'local');

        $companyId = $owner->company_id ?? Auth::user()?->company_id;

        $pathContext = "attachments/{$companyId}/" . class_basename($owner) . "/{$owner->getKey()}/{$typeValue}/" . date('Y/m');
        
        $originalName   = $file->getClientOriginalName();
        $extension      = $file->getClientOriginalExtension();
        $mimeType       = $file->getClientMimeType();
        $sizeBytes      = $file->getSize();
        
        // 2. Upload file
        $storedPath = $file->store($pathContext, ['disk' => $disk]);
        $storedName = basename($storedPath);
        
        // Optional checksum calculation (if configured or needed)
        // $checksum = hash_file('sha256', $file->getRealPath());
        $checksum = null;

        return DB::transaction(function () use ($owner, $typeValue, $idempotencyKey, $mode, $disk, $storedPath, $originalName, $storedName, $extension, $mimeType, $sizeBytes, $checksum, $options, $companyId) {
            
            $nextVersion = 1;

            if ($mode === 'single_latest') {
                // Get all current versions for this type/owner and lock them for update
                $currentAttachments = $owner->attachments()
                    ->lockForUpdate()
                    ->where('type', $typeValue)
                    ->where('is_current', true)
                    ->get();
                
                if ($currentAttachments->isNotEmpty()) {
                    // Update the existing current versions to not be current anymore
                    // We also find the max version to increment
                    $maxVersion = $owner->attachments()
                        ->where('type', $typeValue)
                        ->max('version');
                    
                    $nextVersion = ($maxVersion ?? 0) + 1;

                    foreach ($currentAttachments as $current) {
                        $current->update(['is_current' => false]);
                    }
                }
            } else {
                 $maxVersion = $owner->attachments()
                        ->where('type', $typeValue)
                        ->max('version');
                 $nextVersion = ($maxVersion ?? 0) + 1;
            }

            // 3. Create database record
            return $owner->attachments()->create([
                // 'public_id' is auto-generated by HasUlids trait
                'company_id'        => $companyId,
                'type'              => $typeValue,
                'idempotency_key'   => $idempotencyKey,
                'version'           => $nextVersion,
                'is_current'        => true,
                'disk'              => $disk,
                'path'              => $storedPath,
                'original_name'     => $originalName,
                'stored_name'       => $storedName,
                'extension'         => $extension,
                'mime_type'         => $mimeType,
                'size_bytes'        => $sizeBytes,
                'checksum_sha256'   => $checksum,
                'metadata'          => $options['metadata'] ?? null,
                'uploaded_by'       => Auth::id(),
            ]);
        });
    }

    /**
     * Shortcut for replacing the current attachment of a specific type.
     */
    public function replaceCurrent(Model $owner, UploadedFile|TemporaryUploadedFile $file, $type, array $options = []): Attachment
    {
        // Actually the upload method already handles single_latest based on config,
        // but this explicit method can be used to override or make the intent clearer.
        return $this->upload($owner, $file, $type, $options);
    }

    /**
     * Delete an attachment.
     *
     * @param Attachment $attachment
     * @param array $options Options like `force` (bool) physical delete or logical delete.
     * @return bool
     */
    public function delete(Attachment $attachment, array $options = []): bool
    {
        $force = $options['force'] ?? false;
        
        if ($force) {
            Storage::disk($attachment->disk)->delete($attachment->path);
            return $attachment->forceDelete();
        }
        
        $attachment->deleted_by = Auth::id();
        $attachment->save();
        
        return $attachment->delete();
    }

    /**
     * Prepare a download response for the attachment.
     *
     * @param Attachment $attachment
     * @param string|null $asName
     * @return StreamedResponse|null
     */
    public function downloadResponse(Attachment $attachment, ?string $asName = null): ?StreamedResponse
    {
        if (!Storage::disk($attachment->disk)->exists($attachment->path)) {
            return null;
        }

        $name = $asName ?? $attachment->original_name;

        return Storage::disk($attachment->disk)->download($attachment->path, $name);
    }
}
